<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>NpcYFix</AssemblyName>
    <RootNamespace>NpcYFix</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\net6\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\net6\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppspine-csharp">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\Il2CppAssemblies\Il2Cppspine-csharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppspine-unity">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\Il2CppAssemblies\Il2Cppspine-unity.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppAnimationFlow">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\Il2CppAssemblies\Il2CppAnimationFlow.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\Steam\steamapps\common\Kendo\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
